version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    networks:
      - erpsolution-network
    volumes:
      - mongo-data:/data/db

  erp-back:
    image: chemchu/erp-back
    ports:
      - 9090:9090
    networks:
      - erpsolution-network
    depends_on:
      - mongo
      - erp-recommender
    restart: always
    environment:
      - PORT=${BACK_PORT}
      - MONGO_URI=${BACK_MONGO_URI}
      - DATABASE_NAME=${BACK_DATABASE_NAME}
      - JWT_SECRET=${BACK_JWT_SECRET}
      - JWT_HOURS_DURATION=${BACK_JWT_HOURS_DURATION}
      - ERPGATEWAY_URL=${BACK_ERPGATEWAY_URL}

  erp-gateway:
    image: chemchu/erp-gateway
    ports:
      - 80:80
    networks:
      - erpsolution-network
    depends_on:
      - erp-back
    restart: always
    environment:
      - GIN_MODE=${GATEWAY_GIN_MODE}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - ERPBACK_URL=${GATEWAY_ERPBACK_URL}
      - ERPREGISTRATION_URL=${GATEWAY_ERPREGISTRATION_URL}
      - ERPANALYSIS_URL=${GATEWAY_ERPANALYSIS_URL}
      - ERPRECOMMENDER_URL=${GATEWAY_ERPANALYSIS_URL}
      - TIMEZONE=${TIMEZONE}

  erp-registration:
    image: chemchu/erp-registration
    ports:
      - 7070:7070
    networks:
      - erpsolution-network
    depends_on:
      - erp-gateway
    restart: always
    environment:
      - PORT=${REGISTRATION_PORT}
      - USER=${REGISTRATION_USER}
      - SECRET=${REGISTRATION_SECRET}
      - EMAIL=${REGISTRATION_EMAIL}
      - SERVER_PORT=${REGISTRATION_SERVER_PORT}
      - JWT_SECRET=${REGISTRATION_JWT_SECRET}
      - URL=${REGISTRATION_URL}
      - ERPGATEWAY_URL=${REGISTRATION_ERPGATEWAY_URL}

  erp-analytics:
    image: chemchu/erp-analytics
    ports:
      - 6060:6060
    networks:
      - erpsolution-network
    depends_on:
      - erp-gateway
    restart: always

  erp-recommender:
    image: chemchu/erp-recommender
    ports:
      - 5000:5000
    networks:
      - erpsolution-network
    restart: always

networks:
  erpsolution-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
